name: jms_branch mocha test

on:
  push:
    branches: [Jms_branch, main]
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install, build, and test
        run: |
          npm install mocha -g
          npm install dotenv
          pip install jellyfish
          mocha feature1.spec.js
          mocha feature2.spec.js
          mocha feature3.spec.js
          mocha feature4.5.spec.js
        env:
          CI: true
